package tr.com.innova.watcher.icra;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-04-29T17:41:21.206+03:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://khy.legalite.innova.com.tr/icraOlusturService", name = "icraOlusturService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IcraOlusturService {

    @WebMethod
    @WebResult(name = "icraOlusturResponse", targetNamespace = "http://khy.legalite.innova.com.tr/icraOlusturService", partName = "parameters")
    public IcraOlusturResponse icraOlustur(
        @WebParam(partName = "parameters", name = "icraOlustur", targetNamespace = "http://khy.legalite.innova.com.tr/icraOlusturService")
        IcraOlustur parameters
    );
}
