package tr.com.innova.watcher.icra;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-04-29T17:41:21.280+03:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "icraOlusturServiceService", 
                  wsdlLocation = "file:/C:/work/workspace/khy/rest-api/src/main/java/tr/com/innova/legalite/khy/icra/icra.wsdl",
                  targetNamespace = "http://khy.legalite.innova.com.tr/icraOlusturService") 
public class IcraOlusturServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://khy.legalite.innova.com.tr/icraOlusturService", "icraOlusturServiceService");
    public final static QName IcraOlusturServicePort = new QName("http://khy.legalite.innova.com.tr/icraOlusturService", "icraOlusturServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/work/workspace/khy/rest-api/src/main/java/tr/com/innova/legalite/khy/icra/icra.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IcraOlusturServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/work/workspace/khy/rest-api/src/main/java/tr/com/innova/legalite/khy/icra/icra.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IcraOlusturServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IcraOlusturServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IcraOlusturServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public IcraOlusturServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public IcraOlusturServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public IcraOlusturServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IcraOlusturService
     */
    @WebEndpoint(name = "icraOlusturServicePort")
    public IcraOlusturService getIcraOlusturServicePort() {
        return super.getPort(IcraOlusturServicePort, IcraOlusturService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IcraOlusturService
     */
    @WebEndpoint(name = "icraOlusturServicePort")
    public IcraOlusturService getIcraOlusturServicePort(WebServiceFeature... features) {
        return super.getPort(IcraOlusturServicePort, IcraOlusturService.class, features);
    }

}
