package tr.com.innova.watcher.dys;

/**
 * Created by tozyurek on 29.04.2016.
 */
public enum BelgeTipi {
    ARA_KARAR("Ara Karar"),
    BELGE("Belge"),
    BILIRKISI_RAPORU("Bilirkişi Raporu"),
    BORCLU_MEKTUBU("Borçlu Mektubu"),
    CEVABA_CEVAP_DILEKCESI("Cevaba Cevap Dilekçesi"),
    CEVAP_DILEKCESI("Cevap Dilekçesi"),
    DANISTAY_KARARI("Danıştay Kararı"),
    DAVA_DILEKCESI("Dava Dilekçesi"),
    DEKONT("Dekont"),
    DELIL_LISTESI("Delil Listesi"),
    DERKENAR("Derkenar"),
    DILEKCE("Dilekçe"),
    DIGER("Diğer"),
    DURUSMA_TUTANAGI("Duruşma Tutanağı"),
    E_MAIL("E-Mail"),
    EMSAL_YARGITAY_KARARI("Emsal Yargıtay Kararı"),
    FATURA("Fatura"),
    FORM("Form"),
    GEREKCELI_KARAR("Gerekçeli Karar"),
    GIDER_PUSULASI("Gider Pusulası"),
    GONDERILEN_EVRAK("Gönderilen Evrak"),
    GORUSME_KAYITLARI("Görüşme Kayıtları"),
    GORUSME_TUTANAGI("Görüşme Tutanağı"),
    GUNLUK_MUSTERI_LISTESI("Günlük Müşteri Listesi"),
    GUVENLIK_GUCU_TALEBI("Güvenlik Gücü Talebi"),
    GUVENLIK_SERTIFIKASI("Güvenlik Sertifikası"),
    HARC_MAKBUZU("Harç Makbuzu"),
    HASAR_KESIF_TUTANAGI("Hasar Keşif Tutanağı"),
    HASAR_TESPIT_TUTANAGI("Hasar Tespit Tutanağı"),
    HUKUKI_MUTALAA("Hukuki Mütalaa"),
    KAMPANYA_TAAHHUTNAMESI("Kampanya Taahhütnamesi"),
    KAPAK_HESABI("Kapak Hesabı"),
    KARAR("Karar"),
    KARAR_ORNEKLERI("Karar Örnekleri"),
    KEFALETNAME("Kefaletname"),
    KESIF_TUTANAGI("Keşif Tutanağı"),
    KIRA_SOZLESMESI("Kira Sözleşmesi"),
    KOMISYON_KARARI("Komisyon Kararı"),
    MAHKEME_ILAMLARI("Mahkeme İlamları"),
    MAKAM_ONAYI("Makam Onayı"),
    MEHIL_VESIKASI("Mehil Vesikası"),
    MUHTIRA("Muhtıra"),
    MURAFAA("Mürafaa"),
    MUSTAHSIL_MAKBUZU("Müstahsil Makbuzu"),
    MUZEKKERE("Müzekkere"),
    OLAY_YERI_TESPIT_TUTANAGI("Olay Yeri Tespit Tutanağı"),
    PERAKENDE_SATIS_VESIKASI("Perakende Satış Vesikası"),
    REDDIYAT("Reddiyat"),
    SAVCILIK_SIKAYET_DILEKCESI("Savcılık Şikayet Dilekçesi"),
    SERBEST_MESLEK_MAKBUZU("Serbest Meslek Makbuzu"),
    SEVK_IRSALIYESI("Sevk İrsaliyesi"),
    SIGORTA_POLICESI("Sigorta Poliçesi"),
    SOZLESME("Sözleşme"),
    TAAHUTNAME("Taahütname"),
    TASIMA_IRSALIYESI("Taşıma İrsaliyesi"),
    TEBLIGAT("Tebligat"),
    TEMINAT_MEKTUBU("Teminat Mektubu"),
    TEMYIZ_DILEKCESI("Temyiz Dilekçesi"),
    TENSIP_TUTANAGI("Tensip Tutanağı"),
    TEVZI_FORMU("Tevzi Formu"),
    TRAFIK_KAZASI_TESPIT_TUTANAGI("Trafik Kazası Tespit Tutanağı"),
    TUTANAK("Tutanak"),
    TUKETICI_HAKEM_HEYETI_KARARI("Tüketici Hakem Heyeti Kararı"),
    VEKIL_AVUKATLIK_SOZLESMESI("Vekil Avukatlık Sözleşmesi"),
    VEKIL_KULLANICI_BILGI_FORMU("Vekil Kullanıcı Bilgi Formu"),
    VEKIL_VEKALETNAME_ORNEGI("Vekil Vekaletname Örneği"),
    VEKIL_ISTIFA_IBRANAME("Vekil İstifa İbraname"),
    VERGI_MAKBUZLARI("Vergi Makbuzları"),
    YARGITAY_ILAMI("Yargıtay İlamı"),
    YOLCU_LISTESI("Yolcu Listesi"),
    CAGRI_KAGIDI("Çağrı Kağıdı"),
    ODEME_EMRI("Ödeme Emri"),
    UCRET_BORDROSU("Ücret Bordrosu"),
    ICRA_DOSYASI_KAPAK_HESABI("İcra Dosyası Kapak Hesabı"),
    ICRA_EMRI("İcra Emri"),
    IDDIANAME("İddianame"),
    IHBARNAME("İhbarname"),
    IHTARNAME("İhtarname"),
    INCELEME_RAPORU("İnceleme Raporu"),
    INCELEME_TUTANAGI("İnceleme Tutanağı"),
    IRSALIYELI_FATURA("İrsaliyeli Fatura");
    private final String label;

    BelgeTipi(String label) {
        this.label = label;
    }

    public String getLabel() {
        return label;
    }
}
